apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metadata-database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # This is entirely arbitrary for local testing.
  
  volumeName: metadata-database-pv