#!/usr/bin/env bash

# Runs the dev environment for Open Web Drive
# Usage: ./build.sh [--frontend] [--backend] (default: --all)

#TODO: Create functions for test running with -f flag to bypass and for isolated k8s deployment tests.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/ .." && pwd)"

RUN_FRONTEND=false
RUN_BACKEND=false


usage() {
  cat <<EOF
    Usage: $0 [OPTIONS]

      --frontend Start Vite frontend dev server
      --backend  Start Go backend server
      --infra    Deploy terraform / k8s cluster (including database) to localstack
      --all      Starts everything (default)
      -h, --help Show this help
EOF
}

for arg in "$@"; do
  case "$arg" in
    --all) RUN_FRONTEND=true; RUN_BACKEND=true ;;
    --frontend) RUN_FRONTEND=true ;;
    --backend) RUN_BACKEND=true ;;
    -h|--help) usage; exit 0 ;;
    *) echo "[!] error: invalid option '$arg'" >&2; usage >&2; exit 1 ;;
  esac
done

# If no flags are provided then it'll just default to running all the things.
if [ "$RUN_FRONTEND" = false ] && [ "$RUN_BACKEND" = false ]; then
  RUN_FRONTEND=true; RUN_BACKEND=true
fi

# Load backend env from backend/.env (generated by scripts/setup.sh).
# Splits each KEY=VALUE line manually so values containing '&', '?' and '='
# (e.g. BLOB_BUCKET_URL) stay intact.
load_env() {
  local file="$1"
  while IFS= read -r line; do
    case "$line" in
      ''|\#*) continue ;;
    esac
    local key="${line%%=*}"
    local value="${line#*=}"
    export "$key=$value"
  done < "$file"
}

if [ ! -f "$REPO_ROOT/backend/.env" ] || [ ! -f "$REPO_ROOT/frontend/.env" ]; then
  echo "[!] missing .env files. Run: chmod +x scripts/setup.sh && ./scripts/setup.sh" >&2
  exit 1
fi

load_env "$REPO_ROOT/backend/.env"

backend_pid=
frontend_pid=

cleanup() {
  [ -n "$backend_pid" ] && kill "$backend_pid" 2>/dev/null || true
  [ -n "$frontend_pid" ] && kill "$frontend_pid" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

run_backend() {
  echo "[-] starting backend: go run ./cmd/owd"
  ( cd "$REPO_ROOT/backend" && go run ./cmd/owd ) &
  backend_pid=$!
}

run_frontend() {
  echo "[-] starting frontend: npm run dev"
  ( cd "$REPO_ROOT/frontend" && npm run dev ) &
  frontend_pid=$!
}

if [ "$RUN_BACKEND" = true ]; then
  run_backend
fi
if [ "$RUN_FRONTEND" = true ]; then
  run_frontend
fi

echo "[+] dev environment running. Press Ctrl-C to stop both."

# blocks until Ctrl-C or server exits.
wait
cleanup